---
- hosts: all
  remote_user: root
  tasks:
    - name: allow port 22/tcp
      ufw:
        rule: allow
        port: 22
        proto: tcp
    - name: allow port 2376/tcp
      ufw:
        rule: allow
        port: 2376
        proto: tcp
    - name: allow port 2377/tcp
      ufw:
        rule: allow
        port: 2377
        proto: tcp
    - name: allow port 7946/tcp
      ufw:
        rule: allow
        port: 7946
        proto: tcp
    - name: allow port 7946/udp
      ufw:
        rule: allow
        port: 7946
        proto: udp
    - name: allow port 4789/udp
      ufw:
        rule: allow
        port: 4789
        proto: udp
    - name: enable firewall
      ufw:
        state: enabled